
CREATE TABLE RC_USER (
 USER_ID NUMBER PRIMARY KEY,
 EMAIL VARCHAR2(100) UNIQUE,
 PASSWORD VARCHAR2(100),
 USER_TYPE VARCHAR2(20),
 CREATED_AT DATE
);

CREATE TABLE RC_PROFILE (
 PROFILE_ID NUMBER PRIMARY KEY,
 USER_ID NUMBER REFERENCES RC_USER(USER_ID),
 NAME VARCHAR2(100),
 BIO VARCHAR2(200),
 LOCATION VARCHAR2(100),
 WEBSITE VARCHAR2(100)
);

CREATE SEQUENCE RC_USER_SEQ START WITH 1;
CREATE SEQUENCE RC_PROFILE_SEQ START WITH 1;
