/* =========================================================
   RevConnect Database Schema
   Compatible with Oracle 10g
   ========================================================= */

/* ================= SAFE DROPS ================= */

BEGIN EXECUTE IMMEDIATE 'DROP TABLE RC_NOTIFICATION CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE RC_FOLLOWER CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE RC_CONNECTION CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE RC_SHARE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE RC_LIKE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE RC_COMMENT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE RC_POST CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE RC_PROFILE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE RC_USER CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

/* ================= USERS ================= */

CREATE TABLE RC_USER (
    USER_ID     NUMBER PRIMARY KEY,
    EMAIL       VARCHAR2(100) UNIQUE NOT NULL,
    PASSWORD    VARCHAR2(100) NOT NULL,
    USER_TYPE   VARCHAR2(20)
        CHECK (USER_TYPE IN ('PERSONAL','BUSINESS','CREATOR')),
    CREATED_AT  DATE DEFAULT SYSDATE
);

CREATE SEQUENCE RC_USER_SEQ START WITH 1;

/* ================= PROFILES ================= */

CREATE TABLE RC_PROFILE (
    PROFILE_ID        NUMBER PRIMARY KEY,
    USER_ID           NUMBER UNIQUE REFERENCES RC_USER(USER_ID),
    NAME              VARCHAR2(100),
    BIO               VARCHAR2(500),
    LOCATION          VARCHAR2(100),
    WEBSITE           VARCHAR2(100),
    CATEGORY          VARCHAR2(100),
    BUSINESS_ADDRESS  VARCHAR2(255),
    CONTACT_INFO      VARCHAR2(100)
);

CREATE SEQUENCE RC_PROFILE_SEQ START WITH 1;

/* ================= POSTS ================= */

CREATE TABLE RC_POST (
    POST_ID     NUMBER PRIMARY KEY,
    USER_ID     NUMBER REFERENCES RC_USER(USER_ID),
    CONTENT     VARCHAR2(1000),
    HASHTAGS    VARCHAR2(255),
    CREATED_AT  DATE DEFAULT SYSDATE
);

CREATE SEQUENCE RC_POST_SEQ START WITH 1;

/* ================= COMMENTS ================= */

CREATE TABLE RC_COMMENT (
    COMMENT_ID        NUMBER PRIMARY KEY,
    POST_ID           NUMBER REFERENCES RC_POST(POST_ID),
    USER_ID           NUMBER REFERENCES RC_USER(USER_ID),
    PARENT_COMMENT_ID NUMBER,
    CONTENT           VARCHAR2(500),
    CREATED_AT        DATE DEFAULT SYSDATE,
    CONSTRAINT FK_PARENT_COMMENT
        FOREIGN KEY (PARENT_COMMENT_ID)
        REFERENCES RC_COMMENT(COMMENT_ID)
);

CREATE SEQUENCE RC_COMMENT_SEQ START WITH 1;

/* ================= LIKES ================= */

CREATE TABLE RC_LIKE (
    LIKE_ID   NUMBER PRIMARY KEY,
    POST_ID   NUMBER REFERENCES RC_POST(POST_ID),
    USER_ID   NUMBER REFERENCES RC_USER(USER_ID),
    CONSTRAINT UK_LIKE UNIQUE (POST_ID, USER_ID)
);

CREATE SEQUENCE RC_LIKE_SEQ START WITH 1;

/* ================= SHARES ================= */

CREATE TABLE RC_SHARE (
    SHARE_ID    NUMBER PRIMARY KEY,
    POST_ID     NUMBER REFERENCES RC_POST(POST_ID),
    USER_ID     NUMBER REFERENCES RC_USER(USER_ID),
    CREATED_AT  DATE DEFAULT SYSDATE
);

CREATE SEQUENCE RC_SHARE_SEQ START WITH 1;

/* ================= CONNECTIONS ================= */

CREATE TABLE RC_CONNECTION (
    CONNECTION_ID NUMBER PRIMARY KEY,
    REQUESTER_ID  NUMBER REFERENCES RC_USER(USER_ID),
    RECEIVER_ID   NUMBER REFERENCES RC_USER(USER_ID),
    STATUS        VARCHAR2(20)
        CHECK (STATUS IN ('PENDING','ACCEPTED')),
    CREATED_AT    DATE DEFAULT SYSDATE,
    CONSTRAINT UK_CONNECTION UNIQUE (REQUESTER_ID, RECEIVER_ID)
);

CREATE SEQUENCE RC_CONNECTION_SEQ START WITH 1;

/* ================= FOLLOWERS ================= */

CREATE TABLE RC_FOLLOWER (
    FOLLOWER_ID NUMBER REFERENCES RC_USER(USER_ID),
    FOLLOWEE_ID NUMBER REFERENCES RC_USER(USER_ID),
    CREATED_AT  DATE DEFAULT SYSDATE,
    CONSTRAINT PK_FOLLOWER PRIMARY KEY (FOLLOWER_ID, FOLLOWEE_ID)
);

/* ================= NOTIFICATIONS ================= */

CREATE TABLE RC_NOTIFICATION (
    NOTIFICATION_ID NUMBER PRIMARY KEY,
    USER_ID         NUMBER REFERENCES RC_USER(USER_ID),
    MESSAGE         VARCHAR2(255),
    IS_READ         CHAR(1) DEFAULT 'N'
        CHECK (IS_READ IN ('Y','N')),
    CREATED_AT      DATE DEFAULT SYSDATE
);

CREATE SEQUENCE RC_NOTIFICATION_SEQ START WITH 1;

/* ================= END OF FILE ================= */
